// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAIAnswer(arg1, arg2) {
  return window['go']['internal']['App']['GetAIAnswer'](arg1, arg2);
}

export function GetAllDatabases(arg1, arg2, arg3, arg4) {
  return window['go']['internal']['App']['GetAllDatabases'](arg1, arg2, arg3, arg4);
}

export function GetAllTables(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['internal']['App']['GetAllTables'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableStructure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['internal']['App']['GetTableStructure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Greet(arg1) {
  return window['go']['internal']['App']['Greet'](arg1);
}

export function TestDB(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['internal']['App']['TestDB'](arg1, arg2, arg3, arg4, arg5);
}
