// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function GetAIAnswer(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAllDatabases(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function GetAllTables(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<string>>;

export function GetTableStructure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Array<internal.TableColumn>>;

export function Greet(arg1:string):Promise<string>;

export function TestDB(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;
